import React from 'react';
import Head from 'next/head';

export default function HeadImports() {
  return (
    <Head>
      <meta charset='utf-8' />
      <meta
        name='viewport'
        content='width=device-width, initial-scale=1.0, shrink-to-fit=no'
      />
      <title>Home - Doktor</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
      <meta charset='utf-8' />
      <meta
        name='viewport'
        content='width=device-width, initial-scale=1.0, shrink-to-fit=no'
      />
      <link
        rel='stylesheet'
        href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
      />
      <link
        rel='stylesheet'
        href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic'
      />
      <link
        rel='stylesheet'
        href='../../assets/bootstrap/css/bootstrap.min.css'
      />
      <link rel='stylesheet' href='assets/fonts/font-awesome.min.css' />
      <link rel='stylesheet' href='assets/css/Article-List.css' />
      <link rel='stylesheet' href='assets/css/Features-Blue.css' />
      <link rel='stylesheet' href='assets/css/Features-Boxed.css' />
      <link rel='stylesheet' href='assets/css/Global.css' />
      <link rel='stylesheet' href='assets/css/Highlight-Blue.css' />
      <link rel='stylesheet' href='assets/css/Highlight-Phone.css' />
      <link rel='stylesheet' href='assets/css/Projects-Horizontal.css' />
      <link rel='stylesheet' href='assets/css/Team-Boxed.css' />
      <link rel='stylesheet' href='assets/css/Team-Clean.css' />
      <link rel='stylesheet' href='assets/css/Testimonials.css' />
    </Head>
  );
}
